### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by imperez** [kenwheeler/gulp-helper#23]
1. Try to toggle the gulp panel open and close I get the below error

**Atom Version**: 0.204.0
**System**: Mac OS X 10.10.3
**Thrown From**: [gulp-helper](https://github.com/kenwheeler/gulp-helper) package, v4.1.0
### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /Users/rich/Desktop/Dropbox/atom/packages/gulp-helper/lib/gulp-helper-view.coffee:46

ReferenceError: path is not defined
  at /Users/rich/Desktop/Dropbox/atom/packages/gulp-helper/lib/gulp-helper-view.coffee:46:45
  at GulpHelperView.module.exports.GulpHelperView.runGulp (/Users/rich/Desktop/Dropbox/atom/packages/gulp-helper/lib/gulp-helper-view.coffee:41:7)
  at GulpHelperView.module.exports.GulpHelperView.toggle (/Users/rich/Desktop/Dropbox/atom/packages/gulp-helper/lib/gulp-helper-view.coffee:34:8)
  at atom-workspace.<anonymous> (/Users/rich/Desktop/Dropbox/atom/packages/gulp-helper/lib/gulp-helper-view.coffee:16:58)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
     -1:10.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:00.3.0 pane:show-next-item (atom-text-editor.editor.is-focused)
  3x -0:57.8.0 core:move-left (atom-text-editor.editor.is-focused)
 26x -0:56.9.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:53.6.0 core:cut (atom-text-editor.editor.is-focused)
     -0:53 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  3x -0:52.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:50.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:50.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:49.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:48.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:45.6.0 gulp-helper:toggle (atom-text-editor.editor.is-focused)
     -0:28.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:13.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.3.0 core:close (div.settings-view.pane-item)
     -0:05.8.0 gulp-helper:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "language-objective-c",
      "background-tips",
      "bookmarks",
      "language-c",
      "language-clojure",
      "language-go",
      "language-java",
      "language-mustache",
      "language-perl",
      "language-ruby-on-rails",
      "language-toml",
      "metrics",
      "open-on-github",
      "package-generator",
      "timecop",
      "welcome",
      "custom-invisibles",
      "project-manager",
      "php-introspector",
      "php-debug"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.27.9
atom-handlebars, v0.5.0
atom-ternjs, v0.6.3
color-picker, v2.0.2
docblockr, v0.7.2
file-icons, v1.5.5
gulp-helper, v4.1.0
highlight-selected, v0.9.3
language-apache, v1.3.0
language-gitignore, v0.2.0
language-smarty-php, v0.5.0
linter, v0.12.6
linter-eslint, v0.5.8
linter-phpcs, v0.0.15
pigments, v0.3.1
react, v0.11.8
tabs-to-spaces, v0.11.0

# Dev
No dev packages
```

**Comment by mhoyer** [comment]
I saw same issue under Windows 7 x64 with Atom 1.0 and Node 0.12.4. Provided PR fixes issue for me.

**Comment by DanielSundberg** [comment]
I get this as well, when trying to activate "gulp-helper" immediately after installation. Windows 8.1 x64, Atom 1.0.

**Comment by janbaykara** [comment]
Ditto. Mac OSX 10.10.2, Atom 1.0.2

**Comment by kohbo** [comment]
I'm having the same issue on Windows 7 x64, Atom 1.0.2, Node 0.12.7.

**Comment by kornicameister** [comment]
Same error at Windows 8.1 x64, Atom 1.0.2, Node 0.12.7

**Comment by lorthirk** [comment]
Same form me, Windows 8.1 x64, Atom 1.0.2, Node 0.12.7

**Comment by tsbarnes** [comment]
Likewise on Ubuntu 15.04, Atom 1.0.7.

**Comment by samstr** [comment]
Mac OS X Yosemite 10.10.5, Atom 1.0.9

![screen shot 2015-09-01 at 16 03 21](https://cloud.githubusercontent.com/assets/428626/9607795/ffa9758c-50c2-11e5-9331-9216327888e5.png)

**Comment by Mark-Broadhurst** [comment]
And again WinX, Atom 1.0.1, Gulp-helper V5.0.0

**Comment by mhoyer** [comment]
Can anyone confirm my fix? 2d5ac2f

**Comment by ironicnet** [comment]
@mhoyer i added the line with the one in your PR. No big red error message, but the process finish with exit code 1. Just like #5 ... 

Win7. Atom 1.0.11 (installed today). Last version of gulp-helper (5.0)

**Comment by romantolkachyov** [comment]
Same problem, OSX Yosemite
